### PR TITLE
Added the bell sequence and an example

### PR DESCRIPTION
**Pull request by MarxBro**
Just wanted to _ring the ANSI bell_ and added it to the code.
The example is rather unnecessary (quite much as the bell itself) and just for testing it.
Regards.

### CODE REVIEW

**Comment by fidian** [comment]
Merged.  I appreciate the additional functionality.  The bell character is not strictly an ANSI escape sequence, but I'm happy to have it.

I've changed it a slight amount to simply add the bell character (0x07 or ^G) to the output instead of using a second echo at the end.  I hope you don't mind.

Thanks for the additional example!

Mind if I ask why you called the new example "dadoo" instead of "dado"?  I don't know Spanish (I hope I got the language correct) and Google Translate isn't helping me out.

Closing this pull request because the code was merged, though an additional comment that discusses "dadoo" would be welcomed.

**Comment by MarxBro** [comment]
Great! 
I completely forgot to rename it. Me bad, sorry. 
Feel free to call it "dice". Spanish is "dado", the extra "o" is just to avoid an alias I had.
I  changed the name to "dado" into my fork and added the "bell" bit to the README as well. 
If you prefer, I'll do a new pull request.

**Comment by fidian** [comment]
I've renamed it to `dice` and added your change to the `README.md` describing the new option.  Thanks for reminding me that the documentation needed to be updated!

**Comment by MarxBro** [comment]
Awesome!

**Pull request merged**
